version: '3'
services:

  ### Nginx container #########################################

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${PROJECT_FOLDER}:/etc/nginx/html/:rw
      - ./components/nginx/ssl:/etc/nginx/ssl:ro
      - ./components/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./components/nginx/config/conf.d:/etc/nginx/conf.d:ro
      - ./components/nginx/log:/var/log/nginx:rw
    restart: always
    privileged: true
    links:
      - 720dt
    networks:
      - backend
      - frontend

  ### PHP container #########################################

  php:
    build:
      context: ./build/php
      args:
        TIME_ZONE: ${GLOBAL_TIME_ZONE}
        CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
    volumes:
      - ${PROJECT_FOLDER}/hello:/etc/nginx/html:rw
      - ./components/php/config/php.ini:/usr/local/etc/php/php.ini:ro
      - ./components/php/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./components/php/log:/var/log:rw
    restart: always
    privileged: true
    networks:
      - backend

  ### 720dt container #########################################

  720dt:
    container_name: 720dt
    build:
      context: ./build/php
      args:
        TIME_ZONE: ${GLOBAL_TIME_ZONE}
        CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
    volumes:
      - ${PROJECT_FOLDER}/720dt/htdocs:/etc/nginx/html:rw
      - ./components/php/config/php.ini:/usr/local/etc/php/php.ini:ro
      - ./components/php/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./components/php/log:/var/log:rw
    restart: always
    privileged: true
    networks:
      - backend
  ### PHP container #########################################

  mimi:
    build:
      context: ./build/php
      args:
        TIME_ZONE: ${GLOBAL_TIME_ZONE}
        CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
    volumes:
      - ${PROJECT_FOLDER}/mimi:/etc/nginx/html:rw
      - ./components/php/config/php.ini:/usr/local/etc/php/php.ini:ro
      - ./components/php/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./components/php/log:/var/log:rw
    restart: always
    privileged: true
    networks:
      - backend

  ### Mysql container #########################################

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./components/mysql/data:/var/lib/mysql:rw
      - ./components/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./components/mysql/log:/var/log/mysql:rw
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  ### Redis container #########################################

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./components/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./components/redis/log/redis.log:/var/log/redis/redis.log:rw
    restart: always
    privileged: true
    networks:
      - backend

  ### pma container #########################################

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    privileged: true
    environment:
      PMA_HOST: mysql
    networks:
      - backend

  ### jenkins container #########################################

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./jenkins/data/:/var/jenkins_home

  ### Tools container #########################################
  tools:
    container_name: tools
    build:
      context: ./build/tools
      args:
        TIME_ZONE: ${GLOBAL_TIME_ZONE}
        CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
    volumes:
      - ./components/tools/start.sh:/home/start.sh:rw
      - ./backup:/backup:rw
      - ./components/tools/cron.d:/etc/cron.d:rw
      - ./components/tools/my.cnf:/etc/my.cnf:ro
    restart: always
    privileged: true
    networks:
      - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"